[package]
name = "rustjs"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_ast = {version = "0.38.2", features = ["transpiling"] }
deno_core = "0.280.0"
reqwest = "0.12.4"
tokio = { version = "1.37.0", features = ["full"] }

[build-dependencies]
deno_core = "0.280.0"
